FROM golang:1.17-buster

# compile & install librdkafka (1.8.0)
RUN cd /tmp && \
    git clone https://github.com/edenhill/librdkafka.git && \
    cd /tmp/librdkafka && \
    git checkout 9ded5ee && \
    ./configure && \
    make && \
    make install

COPY ./k2ws/ /go/src/k2ws/


RUN cd /go/src/k2ws/ && \
    go mod tidy && \
    go get -d ./... && \
    go build -tags static && \
    cp k2ws /usr/bin/k2ws

CMD cp /usr/bin/k2ws /build/
